services:
  caddy-1:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - redis
  caddy-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - redis
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
